/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Coach (void)
{
  GtkWidget *Coach;
  GtkWidget *fixed1;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button1;
  GtkWidget *label16;

  Coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Coach, 400, 300);
  gtk_window_set_title (GTK_WINDOW (Coach), _("Coach"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Coach), fixed1);

  button2 = gtk_button_new_with_mnemonic (_("Gestion des rendez-vous"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 64, 160);
  gtk_widget_set_size_request (button2, 296, 40);

  button3 = gtk_button_new_with_mnemonic (_("Modifier le profil"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 64, 232);
  gtk_widget_set_size_request (button3, 296, 40);

  button1 = gtk_button_new_with_mnemonic (_("Gestion des s\303\251ances d'entrainement"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 64, 88);
  gtk_widget_set_size_request (button1, 296, 40);

  label16 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Espace coach</b></span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed1), label16, 72, 16);
  gtk_widget_set_size_request (label16, 272, 40);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Coach, Coach, "Coach");
  GLADE_HOOKUP_OBJECT (Coach, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Coach, button2, "button2");
  GLADE_HOOKUP_OBJECT (Coach, button3, "button3");
  GLADE_HOOKUP_OBJECT (Coach, button1, "button1");
  GLADE_HOOKUP_OBJECT (Coach, label16, "label16");

  return Coach;
}

GtkWidget*
create_Sport (void)
{
  GtkWidget *Sport;
  GtkWidget *fixed2;
  GtkWidget *button6;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *treeview1;
  GtkWidget *button4;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3;
  GtkWidget *label2;

  Sport = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Sport, 400, 300);
  gtk_window_set_title (GTK_WINDOW (Sport), _("Sport"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Sport), fixed2);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 8, 264);
  gtk_widget_set_size_request (button6, 88, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button6), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 54, 48);
  gtk_widget_set_size_request (treeview1, 314, 208);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 152, 256);
  gtk_widget_set_size_request (button4, 128, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button4), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\"><b>Gestion des s\303\251ances d'entrainement</b></span>"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 32, 0);
  gtk_widget_set_size_request (label2, 344, 48);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Sport, Sport, "Sport");
  GLADE_HOOKUP_OBJECT (Sport, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Sport, button6, "button6");
  GLADE_HOOKUP_OBJECT (Sport, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Sport, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Sport, image2, "image2");
  GLADE_HOOKUP_OBJECT (Sport, label9, "label9");
  GLADE_HOOKUP_OBJECT (Sport, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Sport, button4, "button4");
  GLADE_HOOKUP_OBJECT (Sport, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Sport, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Sport, image1, "image1");
  GLADE_HOOKUP_OBJECT (Sport, label3, "label3");
  GLADE_HOOKUP_OBJECT (Sport, label2, "label2");

  return Sport;
}

GtkWidget*
create_Ajout (void)
{
  GtkWidget *Ajout;
  GtkWidget *fixed3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *button7;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label14;
  GtkWidget *button8;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label15;
  GtkWidget *label10;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label11;

  Ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajout), _("Ajout d'un cours"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Ajout), fixed3);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 136, 32);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 136, 88);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 136, 144);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 136, 200);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 16, 264);
  gtk_widget_set_size_request (button7, 96, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button7), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox3), label14, FALSE, FALSE, 0);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 160, 256);
  gtk_widget_set_size_request (button8, 136, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button8), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("<b>Cours :</b>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 56, 32);
  gtk_widget_set_size_request (label10, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  label12 = gtk_label_new_with_mnemonic (_("<b>Date :</b>"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 56, 88);
  gtk_widget_set_size_request (label12, 88, 25);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  label13 = gtk_label_new_with_mnemonic (_("<b>Heure :</b>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 40, 144);
  gtk_widget_set_size_request (label13, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  label11 = gtk_label_new_with_mnemonic (_("<b>Nombre de palace :</b>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 0, 200);
  gtk_widget_set_size_request (label11, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label10), entry1);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label12), entry2);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label13), entry3);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label11), entry4);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout, Ajout, "Ajout");
  GLADE_HOOKUP_OBJECT (Ajout, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Ajout, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Ajout, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Ajout, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Ajout, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Ajout, button7, "button7");
  GLADE_HOOKUP_OBJECT (Ajout, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Ajout, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Ajout, image3, "image3");
  GLADE_HOOKUP_OBJECT (Ajout, label14, "label14");
  GLADE_HOOKUP_OBJECT (Ajout, button8, "button8");
  GLADE_HOOKUP_OBJECT (Ajout, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Ajout, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Ajout, image4, "image4");
  GLADE_HOOKUP_OBJECT (Ajout, label15, "label15");
  GLADE_HOOKUP_OBJECT (Ajout, label10, "label10");
  GLADE_HOOKUP_OBJECT (Ajout, label12, "label12");
  GLADE_HOOKUP_OBJECT (Ajout, label13, "label13");
  GLADE_HOOKUP_OBJECT (Ajout, label11, "label11");

  return Ajout;
}

