/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1 (void);
GtkWidget* create_admin (void);
GtkWidget* create_adherant (void);
GtkWidget* create_coach (void);
GtkWidget* create_generaliste (void);
GtkWidget* create_nutritionniste (void);
GtkWidget* create_kinesitherapeute (void);
