/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *button1;
  GtkWidget *label9;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Login"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 136, 80);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 136, 120);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label1 = gtk_label_new (_("Username :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 24, 80);
  gtk_widget_set_size_request (label1, 104, 23);

  label2 = gtk_label_new (_("Password :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 32, 120);
  gtk_widget_set_size_request (label2, 88, 32);

  button1 = gtk_button_new_with_mnemonic (_("Login"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 184, 168);
  gtk_widget_set_size_request (button1, 68, 29);

  label9 = gtk_label_new ("");
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 24, 216);
  gtk_widget_set_size_request (label9, 408, 80);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, label9, "label9");

  return window1;
}

GtkWidget*
create_admin (void)
{
  GtkWidget *admin;
  GtkWidget *fixed2;
  GtkWidget *label3;

  admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (admin), _("admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (admin), fixed2);

  label3 = gtk_label_new (_("Bienvenu dans l'espace admin "));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 64, 88);
  gtk_widget_set_size_request (label3, 288, 112);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (admin, admin, "admin");
  GLADE_HOOKUP_OBJECT (admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (admin, label3, "label3");

  return admin;
}

GtkWidget*
create_adherant (void)
{
  GtkWidget *adherant;
  GtkWidget *fixed3;
  GtkWidget *label4;

  adherant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (adherant), _("adh\303\251rant"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (adherant), fixed3);

  label4 = gtk_label_new (_("Bienvenu dans l'espace adh\303\251rant"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 72, 96);
  gtk_widget_set_size_request (label4, 272, 104);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (adherant, adherant, "adherant");
  GLADE_HOOKUP_OBJECT (adherant, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (adherant, label4, "label4");

  return adherant;
}

GtkWidget*
create_coach (void)
{
  GtkWidget *coach;
  GtkWidget *fixed4;
  GtkWidget *label5;

  coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (coach), _("coach"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (coach), fixed4);

  label5 = gtk_label_new (_("Bienvenu dans l'espace Coach"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed4), label5, 48, 104);
  gtk_widget_set_size_request (label5, 320, 88);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (coach, coach, "coach");
  GLADE_HOOKUP_OBJECT (coach, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (coach, label5, "label5");

  return coach;
}

GtkWidget*
create_generaliste (void)
{
  GtkWidget *generaliste;
  GtkWidget *fixed5;
  GtkWidget *label6;

  generaliste = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (generaliste), _("g\303\251neraliste"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (generaliste), fixed5);

  label6 = gtk_label_new (_("Bienvenu dans l'espace M\303\251decin g\303\251neraliste"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed5), label6, -16, 0);
  gtk_widget_set_size_request (label6, 424, 304);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (generaliste, generaliste, "generaliste");
  GLADE_HOOKUP_OBJECT (generaliste, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (generaliste, label6, "label6");

  return generaliste;
}

GtkWidget*
create_nutritionniste (void)
{
  GtkWidget *nutritionniste;
  GtkWidget *fixed6;
  GtkWidget *label7;

  nutritionniste = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (nutritionniste), _("nutritionniste"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (nutritionniste), fixed6);

  label7 = gtk_label_new (_("Bienvenu dans l'espace M\303\251decin nutritionniste"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed6), label7, 8, 8);
  gtk_widget_set_size_request (label7, 400, 296);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (nutritionniste, nutritionniste, "nutritionniste");
  GLADE_HOOKUP_OBJECT (nutritionniste, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (nutritionniste, label7, "label7");

  return nutritionniste;
}

GtkWidget*
create_kinesitherapeute (void)
{
  GtkWidget *kinesitherapeute;
  GtkWidget *fixed7;
  GtkWidget *label8;

  kinesitherapeute = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (kinesitherapeute), _("kin\303\251sith\303\251rapeute"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (kinesitherapeute), fixed7);

  label8 = gtk_label_new (_("Bienvenu dans l'espace Kin\303\251sith\303\251rapeute"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed7), label8, 8, 8);
  gtk_widget_set_size_request (label8, 384, 288);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (kinesitherapeute, kinesitherapeute, "kinesitherapeute");
  GLADE_HOOKUP_OBJECT (kinesitherapeute, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (kinesitherapeute, label8, "label8");

  return kinesitherapeute;
}

