/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Coach (void)
{
  GtkWidget *Coach;
  GtkWidget *fixed1;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *label16;

  Coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Coach, 500, 400);
  gtk_window_set_title (GTK_WINDOW (Coach), _("Coach"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Coach), fixed1);

  button1 = gtk_button_new_with_mnemonic (_("Gestion des s\303\251ances d'entrainement"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 64, 88);
  gtk_widget_set_size_request (button1, 296, 40);

  button2 = gtk_button_new_with_mnemonic (_("Gestion des rendez-vous"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 64, 160);
  gtk_widget_set_size_request (button2, 296, 40);

  button3 = gtk_button_new_with_mnemonic (_("Modifier le profil"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed1), button3, 64, 232);
  gtk_widget_set_size_request (button3, 296, 40);

  label16 = gtk_label_new_with_mnemonic (_("<span foreground=\"red\"><b>Espace coach</b></span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed1), label16, 72, 16);
  gtk_widget_set_size_request (label16, 272, 40);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Coach, Coach, "Coach");
  GLADE_HOOKUP_OBJECT (Coach, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Coach, button1, "button1");
  GLADE_HOOKUP_OBJECT (Coach, button2, "button2");
  GLADE_HOOKUP_OBJECT (Coach, button3, "button3");
  GLADE_HOOKUP_OBJECT (Coach, label16, "label16");

  return Coach;
}

GtkWidget*
create_Sport (void)
{
  GtkWidget *Sport;
  GtkWidget *fixed2;
  GtkWidget *button6;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *treeview500;
  GtkWidget *button4;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label3;
  GtkWidget *list_upd;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label40;
  GtkWidget *label2;

  Sport = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Sport, 500, 400);
  gtk_window_set_title (GTK_WINDOW (Sport), _("Sport"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Sport), fixed2);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 8, 264);
  gtk_widget_set_size_request (button6, 88, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button6), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  treeview500 = gtk_tree_view_new ();
  gtk_widget_show (treeview500);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview500, 17, 48);
  gtk_widget_set_size_request (treeview500, 520, 208);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 152, 256);
  gtk_widget_set_size_request (button4, 128, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button4), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  list_upd = gtk_button_new ();
  gtk_widget_show (list_upd);
  gtk_fixed_put (GTK_FIXED (fixed2), list_upd, 352, 264);
  gtk_widget_set_size_request (list_upd, 120, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (list_upd), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox8), label40, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("<span foreground=\"blue\"><b>Gestion des s\303\251ances d'entrainement</b></span>"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 32, 0);
  gtk_widget_set_size_request (label2, 344, 48);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) list_upd, "clicked",
                    G_CALLBACK (on_list_upd_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Sport, Sport, "Sport");
  GLADE_HOOKUP_OBJECT (Sport, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Sport, button6, "button6");
  GLADE_HOOKUP_OBJECT (Sport, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Sport, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Sport, image2, "image2");
  GLADE_HOOKUP_OBJECT (Sport, label9, "label9");
  GLADE_HOOKUP_OBJECT (Sport, treeview500, "treeview500");
  GLADE_HOOKUP_OBJECT (Sport, button4, "button4");
  GLADE_HOOKUP_OBJECT (Sport, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Sport, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Sport, image1, "image1");
  GLADE_HOOKUP_OBJECT (Sport, label3, "label3");
  GLADE_HOOKUP_OBJECT (Sport, list_upd, "list_upd");
  GLADE_HOOKUP_OBJECT (Sport, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Sport, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Sport, image8, "image8");
  GLADE_HOOKUP_OBJECT (Sport, label40, "label40");
  GLADE_HOOKUP_OBJECT (Sport, label2, "label2");

  return Sport;
}

GtkWidget*
create_Ajout (void)
{
  GtkWidget *Ajout;
  GtkWidget *fixed3;
  GtkWidget *label10;
  GtkObject *spinbutton502_adj;
  GtkWidget *spinbutton502;
  GtkObject *spinbutton503_adj;
  GtkWidget *spinbutton503;
  GtkWidget *label12;
  GtkObject *spinbutton504_adj;
  GtkWidget *spinbutton504;
  GtkObject *spinbutton505_adj;
  GtkWidget *spinbutton505;
  GtkObject *spinbutton506_adj;
  GtkWidget *spinbutton506;
  GtkWidget *label22;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *label13;
  GtkWidget *button7;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label14;
  GtkWidget *label19;
  GtkWidget *label11;
  GtkWidget *label18;
  GtkWidget *button8;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label15;
  GtkWidget *entry500;
  GtkWidget *label517;
  GtkWidget *combobox500;
  GtkWidget *combobox502;

  Ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajout, 500, 400);
  gtk_window_set_title (GTK_WINDOW (Ajout), _("Ajout d'un cours"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Ajout), fixed3);

  label10 = gtk_label_new_with_mnemonic (_("<b>Cours :</b>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 104, 72);
  gtk_widget_set_size_request (label10, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  spinbutton502_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton502 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton502_adj), 1, 0);
  gtk_widget_show (spinbutton502);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton502, 264, 224);
  gtk_widget_set_size_request (spinbutton502, 60, 27);

  spinbutton503_adj = gtk_adjustment_new (1, 1, 100, 1, 10, 10);
  spinbutton503 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton503_adj), 1, 0);
  gtk_widget_show (spinbutton503);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton503, 264, 272);
  gtk_widget_set_size_request (spinbutton503, 60, 27);

  label12 = gtk_label_new_with_mnemonic (_("<b>Date :</b>"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 24, 120);
  gtk_widget_set_size_request (label12, 88, 25);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  spinbutton504_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton504 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton504_adj), 1, 0);
  gtk_widget_show (spinbutton504);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton504, 144, 120);
  gtk_widget_set_size_request (spinbutton504, 60, 27);

  spinbutton505_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton505 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton505_adj), 1, 0);
  gtk_widget_show (spinbutton505);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton505, 272, 120);
  gtk_widget_set_size_request (spinbutton505, 60, 27);

  spinbutton506_adj = gtk_adjustment_new (1, 2018, 2050, 1, 10, 10);
  spinbutton506 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton506_adj), 1, 0);
  gtk_widget_show (spinbutton506);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton506, 416, 120);
  gtk_widget_set_size_request (spinbutton506, 60, 27);

  label22 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 352, 120);
  gtk_widget_set_size_request (label22, 72, 24);

  label21 = gtk_label_new (_("mois"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed3), label21, 216, 120);
  gtk_widget_set_size_request (label21, 64, 24);

  label20 = gtk_label_new (_("jour"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed3), label20, 96, 120);
  gtk_widget_set_size_request (label20, 56, 24);

  label13 = gtk_label_new_with_mnemonic (_("<b>Heure :</b>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed3), label13, 96, 176);
  gtk_widget_set_size_request (label13, 120, 32);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed3), button7, 8, 352);
  gtk_widget_set_size_request (button7, 112, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button7), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox3), label14, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("<b>Nombre de place max :</b>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed3), label19, 40, 272);
  gtk_widget_set_size_request (label19, 184, 24);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label11 = gtk_label_new_with_mnemonic (_("<b>Nombre de palace :</b>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed3), label11, 80, 224);
  gtk_widget_set_size_request (label11, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  label18 = gtk_label_new_with_mnemonic (_("<b>Id :</b>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed3), label18, 160, 32);
  gtk_widget_set_size_request (label18, 73, 25);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed3), button8, 176, 352);
  gtk_widget_set_size_request (button8, 136, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button8), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox4), label15, FALSE, FALSE, 0);

  entry500 = gtk_entry_new ();
  gtk_widget_show (entry500);
  gtk_fixed_put (GTK_FIXED (fixed3), entry500, 208, 32);
  gtk_widget_set_size_request (entry500, 112, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry500), 8226);

  label517 = gtk_label_new ("");
  gtk_widget_show (label517);
  gtk_fixed_put (GTK_FIXED (fixed3), label517, 224, 304);
  gtk_widget_set_size_request (label517, 280, 40);

  combobox500 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox500);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox500, 176, 72);
  gtk_widget_set_size_request (combobox500, 200, 30);
  GTK_WIDGET_SET_FLAGS (combobox500, GTK_CAN_DEFAULT);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox500), _("RPM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox500), _("BODYCOMBAT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox500), _("BODYPUMP"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox500), _("BODYATTACK"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox500), _("HIT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox500), _("KICKBOXING"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox500), _("CIRCUITTRAINING"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (combobox500), TRUE);

  combobox502 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox502);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox502, 200, 176);
  gtk_widget_set_size_request (combobox502, 130, 28);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox502), _("10==>11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox502), _("11==>12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox502), _("12==>13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox502), _("16==>17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox502), _("17==>18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox502), _("18==>19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox502), _("19==>20"));

  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label19), spinbutton503);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label11), spinbutton502);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label18), entry500);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout, Ajout, "Ajout");
  GLADE_HOOKUP_OBJECT (Ajout, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Ajout, label10, "label10");
  GLADE_HOOKUP_OBJECT (Ajout, spinbutton502, "spinbutton502");
  GLADE_HOOKUP_OBJECT (Ajout, spinbutton503, "spinbutton503");
  GLADE_HOOKUP_OBJECT (Ajout, label12, "label12");
  GLADE_HOOKUP_OBJECT (Ajout, spinbutton504, "spinbutton504");
  GLADE_HOOKUP_OBJECT (Ajout, spinbutton505, "spinbutton505");
  GLADE_HOOKUP_OBJECT (Ajout, spinbutton506, "spinbutton506");
  GLADE_HOOKUP_OBJECT (Ajout, label22, "label22");
  GLADE_HOOKUP_OBJECT (Ajout, label21, "label21");
  GLADE_HOOKUP_OBJECT (Ajout, label20, "label20");
  GLADE_HOOKUP_OBJECT (Ajout, label13, "label13");
  GLADE_HOOKUP_OBJECT (Ajout, button7, "button7");
  GLADE_HOOKUP_OBJECT (Ajout, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Ajout, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Ajout, image3, "image3");
  GLADE_HOOKUP_OBJECT (Ajout, label14, "label14");
  GLADE_HOOKUP_OBJECT (Ajout, label19, "label19");
  GLADE_HOOKUP_OBJECT (Ajout, label11, "label11");
  GLADE_HOOKUP_OBJECT (Ajout, label18, "label18");
  GLADE_HOOKUP_OBJECT (Ajout, button8, "button8");
  GLADE_HOOKUP_OBJECT (Ajout, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Ajout, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Ajout, image4, "image4");
  GLADE_HOOKUP_OBJECT (Ajout, label15, "label15");
  GLADE_HOOKUP_OBJECT (Ajout, entry500, "entry500");
  GLADE_HOOKUP_OBJECT (Ajout, label517, "label517");
  GLADE_HOOKUP_OBJECT (Ajout, combobox500, "combobox500");
  GLADE_HOOKUP_OBJECT (Ajout, combobox502, "combobox502");

  gtk_widget_grab_default (combobox500);
  return Ajout;
}

GtkWidget*
create_mod (void)
{
  GtkWidget *mod;
  GtkWidget *fixed4;
  GtkWidget *label30;
  GtkWidget *label29;
  GtkWidget *label31;
  GtkObject *spinbutton508_adj;
  GtkWidget *spinbutton508;
  GtkObject *spinbutton509_adj;
  GtkWidget *spinbutton509;
  GtkObject *spinbutton510_adj;
  GtkWidget *spinbutton510;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkObject *spinbutton511_adj;
  GtkWidget *spinbutton511;
  GtkObject *spinbutton512_adj;
  GtkWidget *spinbutton512;
  GtkWidget *entry502;
  GtkWidget *combobox505;
  GtkWidget *combobox504;
  GtkWidget *search_acc;
  GtkWidget *EDIT;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label38;
  GtkWidget *des_acc;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label39;

  mod = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mod, 500, 500);
  gtk_window_set_title (GTK_WINDOW (mod), _("Modifier un cours"));
  gtk_window_set_default_size (GTK_WINDOW (mod), 300, 300);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (mod), fixed4);

  label30 = gtk_label_new (_("Cours"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed4), label30, 88, 80);
  gtk_widget_set_size_request (label30, 96, 32);

  label29 = gtk_label_new (_("identifiant : "));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed4), label29, 152, 24);
  gtk_widget_set_size_request (label29, 96, 32);

  label31 = gtk_label_new (_("Date :"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed4), label31, 0, 160);
  gtk_widget_set_size_request (label31, 80, 32);

  spinbutton508_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton508 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton508_adj), 1, 0);
  gtk_widget_show (spinbutton508);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton508, 152, 160);
  gtk_widget_set_size_request (spinbutton508, 60, 27);

  spinbutton509_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton509 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton509_adj), 1, 0);
  gtk_widget_show (spinbutton509);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton509, 304, 160);
  gtk_widget_set_size_request (spinbutton509, 60, 27);

  spinbutton510_adj = gtk_adjustment_new (1, 2018, 2050, 1, 10, 10);
  spinbutton510 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton510_adj), 1, 0);
  gtk_widget_show (spinbutton510);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton510, 480, 160);
  gtk_widget_set_size_request (spinbutton510, 60, 27);

  label32 = gtk_label_new (_("jour :"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed4), label32, 72, 160);
  gtk_widget_set_size_request (label32, 72, 32);

  label33 = gtk_label_new (_("mois :"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed4), label33, 224, 160);
  gtk_widget_set_size_request (label33, 80, 32);

  label34 = gtk_label_new (_("annee :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed4), label34, 384, 160);
  gtk_widget_set_size_request (label34, 104, 32);

  label35 = gtk_label_new (_("Heure :"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed4), label35, 136, 232);
  gtk_widget_set_size_request (label35, 112, 40);

  label36 = gtk_label_new (_("Nombredeplace :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed4), label36, 120, 296);
  gtk_widget_set_size_request (label36, 136, 32);

  label37 = gtk_label_new (_("Nombredeplacemax:"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed4), label37, 104, 352);
  gtk_widget_set_size_request (label37, 168, 32);

  spinbutton511_adj = gtk_adjustment_new (1, 1, 300, 1, 10, 10);
  spinbutton511 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton511_adj), 1, 0);
  gtk_widget_show (spinbutton511);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton511, 272, 296);
  gtk_widget_set_size_request (spinbutton511, 60, 27);

  spinbutton512_adj = gtk_adjustment_new (1, 1, 300, 1, 10, 10);
  spinbutton512 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton512_adj), 1, 0);
  gtk_widget_show (spinbutton512);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton512, 272, 352);
  gtk_widget_set_size_request (spinbutton512, 60, 27);

  entry502 = gtk_entry_new ();
  gtk_widget_show (entry502);
  gtk_fixed_put (GTK_FIXED (fixed4), entry502, 240, 24);
  gtk_widget_set_size_request (entry502, 88, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry502), 8226);

  combobox505 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox505);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox505, 224, 232);
  gtk_widget_set_size_request (combobox505, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox505), _("10==>11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox505), _("11==>12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox505), _("12==>13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox505), _("16==>17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox505), _("17==>18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox505), _("18==>19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox505), _("19==>20"));

  combobox504 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox504);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox504, 168, 80);
  gtk_widget_set_size_request (combobox504, 224, 32);
  GTK_WIDGET_SET_FLAGS (combobox504, GTK_CAN_DEFAULT);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox504), _("RPM"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox504), _("BODYCOMBAT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox504), _("BODYPUMP"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox504), _("BODYATTACK"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox504), _("HIT"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox504), _("KICKBOXING"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox504), _("CIRCUITTRAINING"));
  gtk_combo_box_set_add_tearoffs (GTK_COMBO_BOX (combobox504), TRUE);

  search_acc = gtk_button_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (search_acc);
  gtk_fixed_put (GTK_FIXED (fixed4), search_acc, 24, 432);
  gtk_widget_set_size_request (search_acc, 112, 32);

  EDIT = gtk_button_new ();
  gtk_widget_show (EDIT);
  gtk_fixed_put (GTK_FIXED (fixed4), EDIT, 232, 432);
  gtk_widget_set_size_request (EDIT, 136, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (EDIT), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox6), label38, FALSE, FALSE, 0);

  des_acc = gtk_button_new ();
  gtk_widget_show (des_acc);
  gtk_fixed_put (GTK_FIXED (fixed4), des_acc, 440, 432);
  gtk_widget_set_size_request (des_acc, 120, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (des_acc), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox7), label39, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) search_acc, "clicked",
                    G_CALLBACK (on_search_acc_clicked),
                    NULL);
  g_signal_connect ((gpointer) EDIT, "clicked",
                    G_CALLBACK (on_EDIT_clicked),
                    NULL);
  g_signal_connect ((gpointer) des_acc, "clicked",
                    G_CALLBACK (on_des_acc_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mod, mod, "mod");
  GLADE_HOOKUP_OBJECT (mod, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (mod, label30, "label30");
  GLADE_HOOKUP_OBJECT (mod, label29, "label29");
  GLADE_HOOKUP_OBJECT (mod, label31, "label31");
  GLADE_HOOKUP_OBJECT (mod, spinbutton508, "spinbutton508");
  GLADE_HOOKUP_OBJECT (mod, spinbutton509, "spinbutton509");
  GLADE_HOOKUP_OBJECT (mod, spinbutton510, "spinbutton510");
  GLADE_HOOKUP_OBJECT (mod, label32, "label32");
  GLADE_HOOKUP_OBJECT (mod, label33, "label33");
  GLADE_HOOKUP_OBJECT (mod, label34, "label34");
  GLADE_HOOKUP_OBJECT (mod, label35, "label35");
  GLADE_HOOKUP_OBJECT (mod, label36, "label36");
  GLADE_HOOKUP_OBJECT (mod, label37, "label37");
  GLADE_HOOKUP_OBJECT (mod, spinbutton511, "spinbutton511");
  GLADE_HOOKUP_OBJECT (mod, spinbutton512, "spinbutton512");
  GLADE_HOOKUP_OBJECT (mod, entry502, "entry502");
  GLADE_HOOKUP_OBJECT (mod, combobox505, "combobox505");
  GLADE_HOOKUP_OBJECT (mod, combobox504, "combobox504");
  GLADE_HOOKUP_OBJECT (mod, search_acc, "search_acc");
  GLADE_HOOKUP_OBJECT (mod, EDIT, "EDIT");
  GLADE_HOOKUP_OBJECT (mod, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (mod, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (mod, image6, "image6");
  GLADE_HOOKUP_OBJECT (mod, label38, "label38");
  GLADE_HOOKUP_OBJECT (mod, des_acc, "des_acc");
  GLADE_HOOKUP_OBJECT (mod, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (mod, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (mod, image7, "image7");
  GLADE_HOOKUP_OBJECT (mod, label39, "label39");

  gtk_widget_grab_default (combobox504);
  return mod;
}

