/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *fixed2;
  GtkWidget *fixed3;
  GtkWidget *button1;
  GtkWidget *label4;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("authentification"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window3), fixed1);

  label2 = gtk_label_new (_("LogIn :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 32, 32);
  gtk_widget_set_size_request (label2, 64, 24);

  label3 = gtk_label_new (_("Password : "));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 16, 104);
  gtk_widget_set_size_request (label3, 120, 16);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 136, 32);
  gtk_widget_set_size_request (entry1, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 136, 96);
  gtk_widget_set_size_request (entry2, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_fixed_put (GTK_FIXED (fixed1), fixed2, 96, 304);
  gtk_widget_set_size_request (fixed2, 72, 16);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed1), fixed3, 88, 328);
  gtk_widget_set_size_request (fixed3, 50, 50);

  button1 = gtk_button_new_with_mnemonic (_("Valider"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 160, 192);
  gtk_widget_set_size_request (button1, 96, 40);

  label4 = gtk_label_new (_("Bienvenue"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 48, 296);
  gtk_widget_set_size_request (label4, 112, 25);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window3, label2, "label2");
  GLADE_HOOKUP_OBJECT (window3, label3, "label3");
  GLADE_HOOKUP_OBJECT (window3, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window3, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window3, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, button1, "button1");
  GLADE_HOOKUP_OBJECT (window3, label4, "label4");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed4;
  GtkWidget *fixed5;
  GtkWidget *label5;
  GtkWidget *button2;
  GtkWidget *button4;
  GtkWidget *button5;
  GtkWidget *button3;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4), fixed4);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_fixed_put (GTK_FIXED (fixed4), fixed5, 168, 232);
  gtk_widget_set_size_request (fixed5, 50, 50);

  label5 = gtk_label_new (_("Bienvenue dans l'espace des COACHS"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed4), label5, 240, 0);
  gtk_widget_set_size_request (label5, 304, 48);

  button2 = gtk_button_new_with_mnemonic (_("Rertour"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed4), button2, 624, 504);
  gtk_widget_set_size_request (button2, 96, 48);

  button4 = gtk_button_new_with_mnemonic (_("Cours\n d'entrainements"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 464, 248);
  gtk_widget_set_size_request (button4, 144, 45);

  button5 = gtk_button_new_with_mnemonic (_("Disponibilit\303\251s \ndes coachs"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed4), button5, 464, 320);
  gtk_widget_set_size_request (button5, 144, 45);

  button3 = gtk_button_new_with_mnemonic (_("Profils des Coachs"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed4), button3, 464, 184);
  gtk_widget_set_size_request (button3, 144, 45);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window4, label5, "label5");
  GLADE_HOOKUP_OBJECT (window4, button2, "button2");
  GLADE_HOOKUP_OBJECT (window4, button4, "button4");
  GLADE_HOOKUP_OBJECT (window4, button5, "button5");
  GLADE_HOOKUP_OBJECT (window4, button3, "button3");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed6;
  GtkWidget *scrolledwindow2;
  GtkWidget *treeview1;
  GtkWidget *button6;
  GtkWidget *button11;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window5), fixed6);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed6), scrolledwindow2, 88, 176);
  gtk_widget_set_size_request (scrolledwindow2, 500, 400);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), treeview1);

  button6 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed6), button6, 64, 48);
  gtk_widget_set_size_request (button6, 120, 56);

  button11 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed6), button11, 224, 56);
  gtk_widget_set_size_request (button11, 76, 29);

  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window5, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window5, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window5, button6, "button6");
  GLADE_HOOKUP_OBJECT (window5, button11, "button11");

  return window5;
}

GtkWidget*
create_window6 (void)
{
  GtkWidget *window6;
  GtkWidget *fixed7;
  GtkWidget *fixed9;
  GtkWidget *fixed10;
  GtkWidget *label8;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkWidget *fixed8;
  GtkWidget *label7;
  GtkWidget *label6;
  GtkWidget *button9;
  GtkWidget *button10;

  window6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6), _("window6"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window6), fixed7);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed9, 48, 80);
  gtk_widget_set_size_request (fixed9, 50, 50);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed10, 48, 128);
  gtk_widget_set_size_request (fixed10, 50, 50);

  label8 = gtk_label_new (_("type"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed10), label8, -32, 0);
  gtk_widget_set_size_request (label8, 73, 17);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed7), entry3, 96, 16);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed7), entry4, 96, 64);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed7), entry5, 96, 120);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_fixed_put (GTK_FIXED (fixed7), fixed8, 40, 32);
  gtk_widget_set_size_request (fixed8, 50, 50);

  label7 = gtk_label_new (_("date"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed8), label7, -24, 32);
  gtk_widget_set_size_request (label7, 65, 24);

  label6 = gtk_label_new (_("s\303\251ance"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed7), label6, 8, 16);
  gtk_widget_set_size_request (label6, 73, 25);

  button9 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed7), button9, 272, 200);
  gtk_widget_set_size_request (button9, 104, 37);

  button10 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed7), button10, 280, 256);
  gtk_widget_set_size_request (button10, 96, 29);

  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6, window6, "window6");
  GLADE_HOOKUP_OBJECT (window6, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window6, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window6, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window6, label8, "label8");
  GLADE_HOOKUP_OBJECT (window6, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window6, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window6, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window6, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window6, label7, "label7");
  GLADE_HOOKUP_OBJECT (window6, label6, "label6");
  GLADE_HOOKUP_OBJECT (window6, button9, "button9");
  GLADE_HOOKUP_OBJECT (window6, button10, "button10");

  return window6;
}

