/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Login (void);
GtkWidget* create_Admin (void);
GtkWidget* create_list (void);
GtkWidget* create_add (void);
GtkWidget* create_activ (void);
GtkWidget* create_stats (void);
GtkWidget* create_deals (void);
GtkWidget* create_edit_acc (void);
GtkWidget* create_activ_add (void);
GtkWidget* create_activ_edit (void);
