/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Login (void)
{
  GtkWidget *Login;
  GtkWidget *fixed1;
  GtkWidget *entry2;
  GtkWidget *entry1;
  GtkWidget *password;
  GtkWidget *button;
  GtkWidget *Error;
  GtkWidget *button12;
  GtkWidget *image6;
  GtkWidget *username;

  Login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Login, 400, 300);
  gtk_window_set_title (GTK_WINDOW (Login), _("Login"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Login), fixed1);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 150, 110);
  gtk_widget_set_size_request (entry2, 200, 30);
  gtk_entry_set_visibility (GTK_ENTRY (entry2), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 150, 50);
  gtk_widget_set_size_request (entry1, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  password = gtk_label_new (_("password:"));
  gtk_widget_show (password);
  gtk_fixed_put (GTK_FIXED (fixed1), password, 50, 110);
  gtk_widget_set_size_request (password, 75, 30);

  button = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (button);
  gtk_fixed_put (GTK_FIXED (fixed1), button, 160, 160);
  gtk_widget_set_size_request (button, 80, 40);

  Error = gtk_label_new ("");
  gtk_widget_show (Error);
  gtk_fixed_put (GTK_FIXED (fixed1), Error, 50, 200);
  gtk_widget_set_size_request (Error, 300, 100);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed1), button12, 370, 0);
  gtk_widget_set_size_request (button12, 30, 30);
  gtk_button_set_focus_on_click (GTK_BUTTON (button12), FALSE);

  image6 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (button12), image6);

  username = gtk_label_new (_("username:"));
  gtk_widget_show (username);
  gtk_fixed_put (GTK_FIXED (fixed1), username, 50, 50);
  gtk_widget_set_size_request (username, 75, 30);

  g_signal_connect ((gpointer) button, "clicked",
                    G_CALLBACK (on_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Login, Login, "Login");
  GLADE_HOOKUP_OBJECT (Login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Login, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (Login, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (Login, password, "password");
  GLADE_HOOKUP_OBJECT (Login, button, "button");
  GLADE_HOOKUP_OBJECT (Login, Error, "Error");
  GLADE_HOOKUP_OBJECT (Login, button12, "button12");
  GLADE_HOOKUP_OBJECT (Login, image6, "image6");
  GLADE_HOOKUP_OBJECT (Login, username, "username");

  gtk_widget_grab_default (Login);
  return Login;
}

GtkWidget*
create_Admin (void)
{
  GtkWidget *Admin;
  GtkWidget *fixed2;
  GtkWidget *admin_quit;
  GtkWidget *image8;
  GtkWidget *admin_list;
  GtkWidget *admin_stats;
  GtkWidget *admin_deals;
  GtkWidget *admin_activ;
  GtkWidget *image21;
  GtkWidget *image20;
  GtkWidget *titre_espace_Admin;
  GtkWidget *image22;
  GtkWidget *image23;

  Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Admin, 800, 450);
  gtk_window_set_title (GTK_WINDOW (Admin), _("Espace administrateur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Admin), fixed2);

  admin_quit = gtk_button_new ();
  gtk_widget_show (admin_quit);
  gtk_fixed_put (GTK_FIXED (fixed2), admin_quit, 770, 0);
  gtk_widget_set_size_request (admin_quit, 30, 30);

  image8 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_container_add (GTK_CONTAINER (admin_quit), image8);

  admin_list = gtk_button_new_with_mnemonic (_("Gestion des comptes"));
  gtk_widget_show (admin_list);
  gtk_fixed_put (GTK_FIXED (fixed2), admin_list, 75, 95);
  gtk_widget_set_size_request (admin_list, 250, 50);

  admin_stats = gtk_button_new_with_mnemonic (_("Rapports et statistiques"));
  gtk_widget_show (admin_stats);
  gtk_fixed_put (GTK_FIXED (fixed2), admin_stats, 375, 235);
  gtk_widget_set_size_request (admin_stats, 250, 50);

  admin_deals = gtk_button_new_with_mnemonic (_("Gestion des offres"));
  gtk_widget_show (admin_deals);
  gtk_fixed_put (GTK_FIXED (fixed2), admin_deals, 525, 305);
  gtk_widget_set_size_request (admin_deals, 250, 50);

  admin_activ = gtk_button_new_with_mnemonic (_("Gestion des activit\303\251s"));
  gtk_widget_show (admin_activ);
  gtk_fixed_put (GTK_FIXED (fixed2), admin_activ, 225, 165);
  gtk_widget_set_size_request (admin_activ, 250, 50);

  image21 = gtk_image_new_from_icon_name ("", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed2), image21, 325, 235);
  gtk_widget_set_size_request (image21, 50, 50);

  image20 = gtk_image_new_from_icon_name ("", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed2), image20, 475, 305);
  gtk_widget_set_size_request (image20, 50, 50);

  titre_espace_Admin = gtk_label_new (_("<span foreground=\"blue\"><b>Bienvenue dans l'espace Admin</b></span>"));
  gtk_widget_show (titre_espace_Admin);
  gtk_fixed_put (GTK_FIXED (fixed2), titre_espace_Admin, 250, 20);
  gtk_widget_set_size_request (titre_espace_Admin, 300, 32);
  gtk_label_set_use_markup (GTK_LABEL (titre_espace_Admin), TRUE);

  image22 = gtk_image_new_from_stock ("gtk-orientation-portrait", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed2), image22, 25, 95);
  gtk_widget_set_size_request (image22, 50, 50);

  image23 = gtk_image_new_from_icon_name ("", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed2), image23, 175, 165);
  gtk_widget_set_size_request (image23, 50, 50);

  g_signal_connect ((gpointer) admin_quit, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) admin_list, "clicked",
                    G_CALLBACK (on_admin_list_clicked),
                    NULL);
  g_signal_connect ((gpointer) admin_stats, "clicked",
                    G_CALLBACK (on_admin_stats_clicked),
                    NULL);
  g_signal_connect ((gpointer) admin_deals, "clicked",
                    G_CALLBACK (on_admin_deals_clicked),
                    NULL);
  g_signal_connect ((gpointer) admin_activ, "clicked",
                    G_CALLBACK (on_admin_activ_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Admin, Admin, "Admin");
  GLADE_HOOKUP_OBJECT (Admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Admin, admin_quit, "admin_quit");
  GLADE_HOOKUP_OBJECT (Admin, image8, "image8");
  GLADE_HOOKUP_OBJECT (Admin, admin_list, "admin_list");
  GLADE_HOOKUP_OBJECT (Admin, admin_stats, "admin_stats");
  GLADE_HOOKUP_OBJECT (Admin, admin_deals, "admin_deals");
  GLADE_HOOKUP_OBJECT (Admin, admin_activ, "admin_activ");
  GLADE_HOOKUP_OBJECT (Admin, image21, "image21");
  GLADE_HOOKUP_OBJECT (Admin, image20, "image20");
  GLADE_HOOKUP_OBJECT (Admin, titre_espace_Admin, "titre_espace_Admin");
  GLADE_HOOKUP_OBJECT (Admin, image22, "image22");
  GLADE_HOOKUP_OBJECT (Admin, image23, "image23");

  return Admin;
}

GtkWidget*
create_list (void)
{
  GtkWidget *list;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *list_return;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;
  GtkWidget *list_quit;
  GtkWidget *image5;
  GtkWidget *list_title;
  GtkWidget *image24;
  GtkWidget *list_add;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *list_upd;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image17;
  GtkWidget *label23;

  list = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (list, 800, 450);
  gtk_window_set_title (GTK_WINDOW (list), _("Gestion des comptes "));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (list), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 50, 60);
  gtk_widget_set_size_request (treeview1, 700, 300);

  list_return = gtk_button_new ();
  gtk_widget_show (list_return);
  gtk_fixed_put (GTK_FIXED (fixed3), list_return, 50, 375);
  gtk_widget_set_size_request (list_return, 112, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (list_return), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  list_quit = gtk_button_new ();
  gtk_widget_show (list_quit);
  gtk_fixed_put (GTK_FIXED (fixed3), list_quit, 770, 0);
  gtk_widget_set_size_request (list_quit, 30, 30);

  image5 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_container_add (GTK_CONTAINER (list_quit), image5);

  list_title = gtk_label_new (_("<span foreground=\"blue\"><b>Gestion des comptes</b></span>"));
  gtk_widget_show (list_title);
  gtk_fixed_put (GTK_FIXED (fixed3), list_title, 250, 20);
  gtk_widget_set_size_request (list_title, 300, 32);
  gtk_label_set_use_markup (GTK_LABEL (list_title), TRUE);

  image24 = gtk_image_new_from_stock ("gtk-orientation-portrait", GTK_ICON_SIZE_DIALOG);
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed3), image24, 272, 8);
  gtk_widget_set_size_request (image24, 50, 50);

  list_add = gtk_button_new ();
  gtk_widget_show (list_add);
  gtk_fixed_put (GTK_FIXED (fixed3), list_add, 324, 379);
  gtk_widget_set_size_request (list_add, 152, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (list_add), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  list_upd = gtk_button_new ();
  gtk_widget_show (list_upd);
  gtk_fixed_put (GTK_FIXED (fixed3), list_upd, 598, 379);
  gtk_widget_set_size_request (list_upd, 152, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (list_upd), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image17 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox10), image17, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox10), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) list_return, "clicked",
                    G_CALLBACK (on_list_return_clicked),
                    NULL);
  g_signal_connect ((gpointer) list_quit, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) list_add, "clicked",
                    G_CALLBACK (on_list_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) list_upd, "clicked",
                    G_CALLBACK (on_list_upd_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (list, list, "list");
  GLADE_HOOKUP_OBJECT (list, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (list, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (list, list_return, "list_return");
  GLADE_HOOKUP_OBJECT (list, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (list, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (list, image1, "image1");
  GLADE_HOOKUP_OBJECT (list, label8, "label8");
  GLADE_HOOKUP_OBJECT (list, list_quit, "list_quit");
  GLADE_HOOKUP_OBJECT (list, image5, "image5");
  GLADE_HOOKUP_OBJECT (list, list_title, "list_title");
  GLADE_HOOKUP_OBJECT (list, image24, "image24");
  GLADE_HOOKUP_OBJECT (list, list_add, "list_add");
  GLADE_HOOKUP_OBJECT (list, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (list, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (list, image2, "image2");
  GLADE_HOOKUP_OBJECT (list, label9, "label9");
  GLADE_HOOKUP_OBJECT (list, list_upd, "list_upd");
  GLADE_HOOKUP_OBJECT (list, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (list, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (list, image17, "image17");
  GLADE_HOOKUP_OBJECT (list, label23, "label23");

  return list;
}

GtkWidget*
create_add (void)
{
  GtkWidget *add;
  GtkWidget *fixed4;
  GtkWidget *add_ent_nom;
  GtkWidget *add_ent_prenom;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label7;
  GtkWidget *label13;
  GtkWidget *add_ent_id;
  GtkWidget *label1;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *combobox1;
  GtkWidget *add_return;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label10;
  GtkWidget *add_ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label11;
  GtkWidget *add_quit;
  GtkWidget *image7;

  add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (add, 800, 450);
  gtk_window_set_title (GTK_WINDOW (add), _("Ajouter un compte"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (add), fixed4);

  add_ent_nom = gtk_entry_new ();
  gtk_widget_show (add_ent_nom);
  gtk_fixed_put (GTK_FIXED (fixed4), add_ent_nom, 300, 100);
  gtk_widget_set_size_request (add_ent_nom, 300, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (add_ent_nom), 8226);

  add_ent_prenom = gtk_entry_new ();
  gtk_widget_show (add_ent_prenom);
  gtk_fixed_put (GTK_FIXED (fixed4), add_ent_prenom, 300, 150);
  gtk_widget_set_size_request (add_ent_prenom, 300, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (add_ent_prenom), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1, 300, 200);
  gtk_widget_set_size_request (spinbutton1, 60, 30);

  spinbutton3_adj = gtk_adjustment_new (1997, 1950, 2018, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3, 525, 200);
  gtk_widget_set_size_request (spinbutton3, 75, 30);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 410, 200);
  gtk_widget_set_size_request (spinbutton2, 60, 30);

  label4 = gtk_label_new (_("Jour"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed4), label4, 260, 200);
  gtk_widget_set_size_request (label4, 40, 30);

  label5 = gtk_label_new (_("Mois"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed4), label5, 370, 200);
  gtk_widget_set_size_request (label5, 40, 30);

  label6 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed4), label6, 475, 200);
  gtk_widget_set_size_request (label6, 45, 30);

  label2 = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed4), label2, 150, 150);
  gtk_widget_set_size_request (label2, 100, 30);
  gtk_misc_set_alignment (GTK_MISC (label2), 1, 0.5);

  label3 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed4), label3, 50, 200);
  gtk_widget_set_size_request (label3, 200, 30);
  gtk_misc_set_alignment (GTK_MISC (label3), 1, 0.5);

  label7 = gtk_label_new (_("Role:"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed4), label7, 50, 250);
  gtk_widget_set_size_request (label7, 200, 30);
  gtk_misc_set_alignment (GTK_MISC (label7), 1, 0.5);

  label13 = gtk_label_new (_("<span foreground=\"blue\"><b>Ajouter un compte </b></span>"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed4), label13, 320, 20);
  gtk_widget_set_size_request (label13, 160, 32);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  add_ent_id = gtk_entry_new ();
  gtk_widget_show (add_ent_id);
  gtk_fixed_put (GTK_FIXED (fixed4), add_ent_id, 300, 50);
  gtk_widget_set_size_request (add_ent_id, 300, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (add_ent_id), 8226);

  label1 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed4), label1, 200, 100);
  gtk_widget_set_size_request (label1, 50, 30);
  gtk_misc_set_alignment (GTK_MISC (label1), 1, 0.5);

  label14 = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 150, 50);
  gtk_widget_set_size_request (label14, 100, 30);
  gtk_misc_set_alignment (GTK_MISC (label14), 1, 0.5);

  label15 = gtk_label_new ("");
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 552, 320);
  gtk_widget_set_size_request (label15, 136, 33);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox1, 300, 250);
  gtk_widget_set_size_request (combobox1, 300, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Adh\303\251rent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("M\303\251dcin_g\303\251n\303\251raliste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("M\303\251decin_nutritionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Kin\303\251sith\303\251rapeute"));

  add_return = gtk_button_new ();
  gtk_widget_show (add_return);
  gtk_fixed_put (GTK_FIXED (fixed4), add_return, 50, 375);
  gtk_widget_set_size_request (add_return, 112, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (add_return), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  add_ajouter = gtk_button_new ();
  gtk_widget_show (add_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed4), add_ajouter, 350, 320);
  gtk_widget_set_size_request (add_ajouter, 152, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (add_ajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox4), label11, FALSE, FALSE, 0);

  add_quit = gtk_button_new ();
  gtk_widget_show (add_quit);
  gtk_fixed_put (GTK_FIXED (fixed4), add_quit, 770, 0);
  gtk_widget_set_size_request (add_quit, 30, 30);

  image7 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (add_quit), image7);

  g_signal_connect ((gpointer) add_return, "clicked",
                    G_CALLBACK (on_add_return_clicked),
                    NULL);
  g_signal_connect ((gpointer) add_ajouter, "clicked",
                    G_CALLBACK (on_add_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) add_quit, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (add, add, "add");
  GLADE_HOOKUP_OBJECT (add, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (add, add_ent_nom, "add_ent_nom");
  GLADE_HOOKUP_OBJECT (add, add_ent_prenom, "add_ent_prenom");
  GLADE_HOOKUP_OBJECT (add, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (add, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (add, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (add, label4, "label4");
  GLADE_HOOKUP_OBJECT (add, label5, "label5");
  GLADE_HOOKUP_OBJECT (add, label6, "label6");
  GLADE_HOOKUP_OBJECT (add, label2, "label2");
  GLADE_HOOKUP_OBJECT (add, label3, "label3");
  GLADE_HOOKUP_OBJECT (add, label7, "label7");
  GLADE_HOOKUP_OBJECT (add, label13, "label13");
  GLADE_HOOKUP_OBJECT (add, add_ent_id, "add_ent_id");
  GLADE_HOOKUP_OBJECT (add, label1, "label1");
  GLADE_HOOKUP_OBJECT (add, label14, "label14");
  GLADE_HOOKUP_OBJECT (add, label15, "label15");
  GLADE_HOOKUP_OBJECT (add, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (add, add_return, "add_return");
  GLADE_HOOKUP_OBJECT (add, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (add, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (add, image3, "image3");
  GLADE_HOOKUP_OBJECT (add, label10, "label10");
  GLADE_HOOKUP_OBJECT (add, add_ajouter, "add_ajouter");
  GLADE_HOOKUP_OBJECT (add, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (add, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (add, image4, "image4");
  GLADE_HOOKUP_OBJECT (add, label11, "label11");
  GLADE_HOOKUP_OBJECT (add, add_quit, "add_quit");
  GLADE_HOOKUP_OBJECT (add, image7, "image7");

  return add;
}

GtkWidget*
create_activ (void)
{
  GtkWidget *activ;
  GtkWidget *fixed7;
  GtkWidget *activ_quit;
  GtkWidget *image12;
  GtkWidget *Activ_title_label;
  GtkWidget *activ_return;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image11;
  GtkWidget *label19;
  GtkWidget *activ_treeview;
  GtkWidget *activ_upd;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image19;
  GtkWidget *label25;
  GtkWidget *activ_add;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image18;
  GtkWidget *label24;
  GtkWidget *image25;

  activ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (activ, 800, 450);
  gtk_window_set_title (GTK_WINDOW (activ), _("Gestion des activit\303\251s"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (activ), fixed7);

  activ_quit = gtk_button_new ();
  gtk_widget_show (activ_quit);
  gtk_fixed_put (GTK_FIXED (fixed7), activ_quit, 770, 0);
  gtk_widget_set_size_request (activ_quit, 30, 30);

  image12 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (activ_quit), image12);

  Activ_title_label = gtk_label_new (_("<span foreground=\"blue\"><b>Gestion des activit\303\251s</b></span>"));
  gtk_widget_show (Activ_title_label);
  gtk_fixed_put (GTK_FIXED (fixed7), Activ_title_label, 250, 20);
  gtk_widget_set_size_request (Activ_title_label, 300, 32);
  gtk_label_set_use_markup (GTK_LABEL (Activ_title_label), TRUE);

  activ_return = gtk_button_new ();
  gtk_widget_show (activ_return);
  gtk_fixed_put (GTK_FIXED (fixed7), activ_return, 50, 375);
  gtk_widget_set_size_request (activ_return, 112, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (activ_return), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox7), image11, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox7), label19, FALSE, FALSE, 0);

  activ_treeview = gtk_tree_view_new ();
  gtk_widget_show (activ_treeview);
  gtk_fixed_put (GTK_FIXED (fixed7), activ_treeview, 50, 60);
  gtk_widget_set_size_request (activ_treeview, 700, 300);

  activ_upd = gtk_button_new ();
  gtk_widget_show (activ_upd);
  gtk_fixed_put (GTK_FIXED (fixed7), activ_upd, 598, 379);
  gtk_widget_set_size_request (activ_upd, 152, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (activ_upd), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image19 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox12), image19, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox12), label25, FALSE, FALSE, 0);

  activ_add = gtk_button_new ();
  gtk_widget_show (activ_add);
  gtk_fixed_put (GTK_FIXED (fixed7), activ_add, 324, 379);
  gtk_widget_set_size_request (activ_add, 152, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (activ_add), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image18 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox11), image18, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox11), label24, FALSE, FALSE, 0);

  image25 = gtk_image_new_from_icon_name ("", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed7), image25, 272, 8);
  gtk_widget_set_size_request (image25, 50, 50);

  g_signal_connect ((gpointer) activ_quit, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) activ_return, "clicked",
                    G_CALLBACK (on_activ_return_clicked),
                    NULL);
  g_signal_connect ((gpointer) activ_upd, "clicked",
                    G_CALLBACK (on_activ_upd_clicked),
                    NULL);
  g_signal_connect ((gpointer) activ_add, "clicked",
                    G_CALLBACK (on_activ_add_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (activ, activ, "activ");
  GLADE_HOOKUP_OBJECT (activ, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (activ, activ_quit, "activ_quit");
  GLADE_HOOKUP_OBJECT (activ, image12, "image12");
  GLADE_HOOKUP_OBJECT (activ, Activ_title_label, "Activ_title_label");
  GLADE_HOOKUP_OBJECT (activ, activ_return, "activ_return");
  GLADE_HOOKUP_OBJECT (activ, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (activ, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (activ, image11, "image11");
  GLADE_HOOKUP_OBJECT (activ, label19, "label19");
  GLADE_HOOKUP_OBJECT (activ, activ_treeview, "activ_treeview");
  GLADE_HOOKUP_OBJECT (activ, activ_upd, "activ_upd");
  GLADE_HOOKUP_OBJECT (activ, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (activ, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (activ, image19, "image19");
  GLADE_HOOKUP_OBJECT (activ, label25, "label25");
  GLADE_HOOKUP_OBJECT (activ, activ_add, "activ_add");
  GLADE_HOOKUP_OBJECT (activ, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (activ, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (activ, image18, "image18");
  GLADE_HOOKUP_OBJECT (activ, label24, "label24");
  GLADE_HOOKUP_OBJECT (activ, image25, "image25");

  return activ;
}

GtkWidget*
create_stats (void)
{
  GtkWidget *stats;
  GtkWidget *fixed6;
  GtkWidget *stats_quit;
  GtkWidget *image13;
  GtkWidget *stats_return;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image10;
  GtkWidget *label18;
  GtkWidget *stats_title;
  GtkWidget *image26;
  GtkWidget *stats_treeview;

  stats = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (stats, 800, 450);
  gtk_window_set_title (GTK_WINDOW (stats), _("Rapports et statistiques"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (stats), fixed6);

  stats_quit = gtk_button_new ();
  gtk_widget_show (stats_quit);
  gtk_fixed_put (GTK_FIXED (fixed6), stats_quit, 770, 0);
  gtk_widget_set_size_request (stats_quit, 30, 30);

  image13 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (stats_quit), image13);

  stats_return = gtk_button_new ();
  gtk_widget_show (stats_return);
  gtk_fixed_put (GTK_FIXED (fixed6), stats_return, 50, 375);
  gtk_widget_set_size_request (stats_return, 112, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (stats_return), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox6), image10, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox6), label18, FALSE, FALSE, 0);

  stats_title = gtk_label_new (_("<span foreground=\"blue\"><b>Rapports et statistiques</b></span>"));
  gtk_widget_show (stats_title);
  gtk_fixed_put (GTK_FIXED (fixed6), stats_title, 250, 20);
  gtk_widget_set_size_request (stats_title, 300, 32);
  gtk_label_set_use_markup (GTK_LABEL (stats_title), TRUE);

  image26 = gtk_image_new_from_icon_name ("", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed6), image26, 256, 8);
  gtk_widget_set_size_request (image26, 50, 50);

  stats_treeview = gtk_tree_view_new ();
  gtk_widget_show (stats_treeview);
  gtk_fixed_put (GTK_FIXED (fixed6), stats_treeview, 50, 60);
  gtk_widget_set_size_request (stats_treeview, 700, 300);

  g_signal_connect ((gpointer) stats_quit, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) stats_return, "clicked",
                    G_CALLBACK (on_stats_return_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (stats, stats, "stats");
  GLADE_HOOKUP_OBJECT (stats, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (stats, stats_quit, "stats_quit");
  GLADE_HOOKUP_OBJECT (stats, image13, "image13");
  GLADE_HOOKUP_OBJECT (stats, stats_return, "stats_return");
  GLADE_HOOKUP_OBJECT (stats, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (stats, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (stats, image10, "image10");
  GLADE_HOOKUP_OBJECT (stats, label18, "label18");
  GLADE_HOOKUP_OBJECT (stats, stats_title, "stats_title");
  GLADE_HOOKUP_OBJECT (stats, image26, "image26");
  GLADE_HOOKUP_OBJECT (stats, stats_treeview, "stats_treeview");

  return stats;
}

GtkWidget*
create_deals (void)
{
  GtkWidget *deals;
  GtkWidget *fixed5;
  GtkWidget *deals_title;
  GtkWidget *deals_quit;
  GtkWidget *image14;
  GtkWidget *deals_return;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image9;
  GtkWidget *label17;
  GtkWidget *image27;
  GtkWidget *deals_treeview;
  GtkWidget *deals_upd;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image29;
  GtkWidget *label27;
  GtkWidget *deals_add;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image28;
  GtkWidget *label26;

  deals = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (deals, 800, 450);
  gtk_window_set_title (GTK_WINDOW (deals), _("Gestion des offres"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (deals), fixed5);

  deals_title = gtk_label_new (_("<span foreground=\"blue\"><b>Gestion des offres</b></span>"));
  gtk_widget_show (deals_title);
  gtk_fixed_put (GTK_FIXED (fixed5), deals_title, 250, 20);
  gtk_widget_set_size_request (deals_title, 300, 32);
  gtk_label_set_use_markup (GTK_LABEL (deals_title), TRUE);

  deals_quit = gtk_button_new ();
  gtk_widget_show (deals_quit);
  gtk_fixed_put (GTK_FIXED (fixed5), deals_quit, 770, 0);
  gtk_widget_set_size_request (deals_quit, 30, 30);

  image14 = gtk_image_new_from_stock ("gtk-no", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (deals_quit), image14);

  deals_return = gtk_button_new ();
  gtk_widget_show (deals_return);
  gtk_fixed_put (GTK_FIXED (fixed5), deals_return, 50, 375);
  gtk_widget_set_size_request (deals_return, 112, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (deals_return), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox5), image9, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox5), label17, FALSE, FALSE, 0);

  image27 = gtk_image_new_from_icon_name ("", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed5), image27, 272, 8);
  gtk_widget_set_size_request (image27, 50, 50);

  deals_treeview = gtk_tree_view_new ();
  gtk_widget_show (deals_treeview);
  gtk_fixed_put (GTK_FIXED (fixed5), deals_treeview, 50, 60);
  gtk_widget_set_size_request (deals_treeview, 700, 300);

  deals_upd = gtk_button_new ();
  gtk_widget_show (deals_upd);
  gtk_fixed_put (GTK_FIXED (fixed5), deals_upd, 598, 379);
  gtk_widget_set_size_request (deals_upd, 152, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (deals_upd), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image29 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image29);
  gtk_box_pack_start (GTK_BOX (hbox14), image29, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox14), label27, FALSE, FALSE, 0);

  deals_add = gtk_button_new ();
  gtk_widget_show (deals_add);
  gtk_fixed_put (GTK_FIXED (fixed5), deals_add, 324, 379);
  gtk_widget_set_size_request (deals_add, 152, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (deals_add), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image28 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox13), image28, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox13), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) deals_quit, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) deals_return, "clicked",
                    G_CALLBACK (on_deals_return_clicked),
                    NULL);
  g_signal_connect ((gpointer) deals_upd, "clicked",
                    G_CALLBACK (on_deals_upd_clicked),
                    NULL);
  g_signal_connect ((gpointer) deals_add, "clicked",
                    G_CALLBACK (on_deals_add_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (deals, deals, "deals");
  GLADE_HOOKUP_OBJECT (deals, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (deals, deals_title, "deals_title");
  GLADE_HOOKUP_OBJECT (deals, deals_quit, "deals_quit");
  GLADE_HOOKUP_OBJECT (deals, image14, "image14");
  GLADE_HOOKUP_OBJECT (deals, deals_return, "deals_return");
  GLADE_HOOKUP_OBJECT (deals, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (deals, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (deals, image9, "image9");
  GLADE_HOOKUP_OBJECT (deals, label17, "label17");
  GLADE_HOOKUP_OBJECT (deals, image27, "image27");
  GLADE_HOOKUP_OBJECT (deals, deals_treeview, "deals_treeview");
  GLADE_HOOKUP_OBJECT (deals, deals_upd, "deals_upd");
  GLADE_HOOKUP_OBJECT (deals, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (deals, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (deals, image29, "image29");
  GLADE_HOOKUP_OBJECT (deals, label27, "label27");
  GLADE_HOOKUP_OBJECT (deals, deals_add, "deals_add");
  GLADE_HOOKUP_OBJECT (deals, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (deals, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (deals, image28, "image28");
  GLADE_HOOKUP_OBJECT (deals, label26, "label26");

  return deals;
}

GtkWidget*
create_edit_acc (void)
{
  GtkWidget *edit_acc;
  GtkWidget *fixed8;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *entry5;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label37;
  GtkWidget *combobox2;
  GtkWidget *button15;
  GtkWidget *image32;
  GtkWidget *search_acc;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image34;
  GtkWidget *label40;
  GtkWidget *edit_acc_return;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image30;
  GtkWidget *label38;
  GtkWidget *edit_account;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image33;
  GtkWidget *label39;

  edit_acc = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (edit_acc, 800, 450);
  gtk_window_set_title (GTK_WINDOW (edit_acc), _("window1"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (edit_acc), fixed8);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed8), entry3, 300, 100);
  gtk_widget_set_size_request (entry3, 300, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed8), entry4, 300, 150);
  gtk_widget_set_size_request (entry4, 300, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton4, 300, 200);
  gtk_widget_set_size_request (spinbutton4, 60, 30);

  spinbutton5_adj = gtk_adjustment_new (1997, 1950, 2018, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton5, 525, 200);
  gtk_widget_set_size_request (spinbutton5, 75, 30);

  spinbutton6_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton6, 410, 200);
  gtk_widget_set_size_request (spinbutton6, 60, 30);

  label28 = gtk_label_new (_("Jour"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed8), label28, 260, 200);
  gtk_widget_set_size_request (label28, 40, 30);

  label29 = gtk_label_new (_("Mois"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed8), label29, 370, 200);
  gtk_widget_set_size_request (label29, 40, 30);

  label30 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed8), label30, 475, 200);
  gtk_widget_set_size_request (label30, 45, 30);

  label31 = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed8), label31, 150, 150);
  gtk_widget_set_size_request (label31, 100, 30);
  gtk_misc_set_alignment (GTK_MISC (label31), 1, 0.5);

  label32 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed8), label32, 50, 200);
  gtk_widget_set_size_request (label32, 200, 30);
  gtk_misc_set_alignment (GTK_MISC (label32), 1, 0.5);

  label33 = gtk_label_new (_("Role:"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed8), label33, 50, 250);
  gtk_widget_set_size_request (label33, 200, 30);
  gtk_misc_set_alignment (GTK_MISC (label33), 1, 0.5);

  label34 = gtk_label_new (_("<span foreground=\"blue\"><b>Ajouter un compte </b></span>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed8), label34, 320, 20);
  gtk_widget_set_size_request (label34, 160, 32);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed8), entry5, 300, 50);
  gtk_widget_set_size_request (entry5, 300, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  label35 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed8), label35, 200, 100);
  gtk_widget_set_size_request (label35, 50, 30);
  gtk_misc_set_alignment (GTK_MISC (label35), 1, 0.5);

  label36 = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed8), label36, 150, 50);
  gtk_widget_set_size_request (label36, 100, 30);
  gtk_misc_set_alignment (GTK_MISC (label36), 1, 0.5);

  label37 = gtk_label_new ("");
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed8), label37, 552, 320);
  gtk_widget_set_size_request (label37, 136, 33);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox2, 300, 250);
  gtk_widget_set_size_request (combobox2, 300, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Adh\303\251rent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Coach"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("M\303\251dcin_g\303\251n\303\251raliste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("M\303\251decin_nutritionniste"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("Kin\303\251sith\303\251rapeute"));

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed8), button15, 770, 0);
  gtk_widget_set_size_request (button15, 30, 30);

  image32 = gtk_image_new_from_stock ("gtk-close", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_container_add (GTK_CONTAINER (button15), image32);

  search_acc = gtk_button_new ();
  gtk_widget_show (search_acc);
  gtk_fixed_put (GTK_FIXED (fixed8), search_acc, 216, 312);
  gtk_widget_set_size_request (search_acc, 88, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (search_acc), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image34 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox17), image34, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox17), label40, FALSE, FALSE, 0);

  edit_acc_return = gtk_button_new ();
  gtk_widget_show (edit_acc_return);
  gtk_fixed_put (GTK_FIXED (fixed8), edit_acc_return, 50, 375);
  gtk_widget_set_size_request (edit_acc_return, 112, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (edit_acc_return), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image30 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox15), image30, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox15), label38, FALSE, FALSE, 0);

  edit_account = gtk_button_new ();
  gtk_widget_show (edit_account);
  gtk_fixed_put (GTK_FIXED (fixed8), edit_account, 350, 320);
  gtk_widget_set_size_request (edit_account, 152, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (edit_account), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image33 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox16), image33, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox16), label39, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) search_acc, "clicked",
                    G_CALLBACK (on_search_acc_clicked),
                    NULL);
  g_signal_connect ((gpointer) edit_acc_return, "clicked",
                    G_CALLBACK (on_edit_acc_return_clicked),
                    NULL);
  g_signal_connect ((gpointer) edit_account, "clicked",
                    G_CALLBACK (on_add_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (edit_acc, edit_acc, "edit_acc");
  GLADE_HOOKUP_OBJECT (edit_acc, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (edit_acc, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (edit_acc, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (edit_acc, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (edit_acc, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (edit_acc, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (edit_acc, label28, "label28");
  GLADE_HOOKUP_OBJECT (edit_acc, label29, "label29");
  GLADE_HOOKUP_OBJECT (edit_acc, label30, "label30");
  GLADE_HOOKUP_OBJECT (edit_acc, label31, "label31");
  GLADE_HOOKUP_OBJECT (edit_acc, label32, "label32");
  GLADE_HOOKUP_OBJECT (edit_acc, label33, "label33");
  GLADE_HOOKUP_OBJECT (edit_acc, label34, "label34");
  GLADE_HOOKUP_OBJECT (edit_acc, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (edit_acc, label35, "label35");
  GLADE_HOOKUP_OBJECT (edit_acc, label36, "label36");
  GLADE_HOOKUP_OBJECT (edit_acc, label37, "label37");
  GLADE_HOOKUP_OBJECT (edit_acc, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (edit_acc, button15, "button15");
  GLADE_HOOKUP_OBJECT (edit_acc, image32, "image32");
  GLADE_HOOKUP_OBJECT (edit_acc, search_acc, "search_acc");
  GLADE_HOOKUP_OBJECT (edit_acc, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (edit_acc, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (edit_acc, image34, "image34");
  GLADE_HOOKUP_OBJECT (edit_acc, label40, "label40");
  GLADE_HOOKUP_OBJECT (edit_acc, edit_acc_return, "edit_acc_return");
  GLADE_HOOKUP_OBJECT (edit_acc, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (edit_acc, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (edit_acc, image30, "image30");
  GLADE_HOOKUP_OBJECT (edit_acc, label38, "label38");
  GLADE_HOOKUP_OBJECT (edit_acc, edit_account, "edit_account");
  GLADE_HOOKUP_OBJECT (edit_acc, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (edit_acc, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (edit_acc, image33, "image33");
  GLADE_HOOKUP_OBJECT (edit_acc, label39, "label39");

  return edit_acc;
}

